function out = generate_pure_literature_reference(varargin)
%GENERATE_PURE_LITERATURE_REFERENCE Code generator for the B1 benchmark RHS.
%
%   OUT = GENERATE_PURE_LITERATURE_REFERENCE(...)
%
%   Single-source generation chain (audit hardening, part C):
%     models/literature_reference/model_definition.json   (canonical, machine-readable)
%          |
%          v  this generator (deterministic, byte-stable output)
%     matlab/generated/rhs_pure_literature_reference.m    (do not edit by hand)
%
%   The canonical definition contains state IDs/order, rate IDs, the exact
%   MATLAB rate-law and ODE expressions, parameter references, units, the
%   stoichiometric matrix (with average-species divisors) and the observable
%   mappings. The generator:
%     1. emits the RHS from the definition (no timestamp -> byte-stable);
%     2. embeds the SHA-256 of the definition in the generated header;
%     3. when writing the default (checked-in) path, re-evaluates the newly
%        written RHS at random states and verifies it against the
%        stoichiometric matrix (S*rates)./divisor to floating-point
%        roundoff — a structural cross-check between the two
%        representations of the same equations.
%
%   Name-value options:
%     'OutputFile'           target path (default: the checked-in generated file).
%                            A non-default path only writes text (used by tests);
%                            the consistency check runs on the default path.
%     'SkipConsistencyCheck' skip step 3 (default false)
%
%   This generator changes NO scientific content: the emitted expressions are
%   the literal paper equations already reviewed against the source PDF.

ip = inputParser;
d0 = fileparts(mfilename('fullpath'));           % .../matlab/codegen
root0 = fileparts(fileparts(d0));                % project root
ip.addParameter('OutputFile', ...
    fullfile(root0, 'matlab', 'generated', 'rhs_pure_literature_reference.m'));
ip.addParameter('SkipConsistencyCheck', false);
ip.parse(varargin{:});
outfile = ip.Results.OutputFile;
do_check = ~ip.Results.SkipConsistencyCheck;

defpath = fullfile(root0, 'models', 'literature_reference', 'model_definition.json');
S = jsondecode(fileread(defpath));
defhash = pure_sha256_file(defpath);

states = sortstruct(S.states, 'index');
rates  = sortstruct(S.rates,  'index');
scg    = sortstruct(S.state_codegen, 'index');
inter  = S.intermediates;

L = {};
L{end+1} = 'function [dydt, rates] = rhs_pure_literature_reference(~, y, p)';
L{end+1} = '%RHS_PURE_LITERATURE_REFERENCE Right-hand side of the Mavelli 2015 PURE model.';
L{end+1} = '% *** AUTO-GENERATED FILE — DO NOT EDIT BY HAND ***';
L{end+1} = '%';
L{end+1} = '%   Generated by       : matlab/codegen/generate_pure_literature_reference.m';
L{end+1} = '%   Canonical source   : models/literature_reference/model_definition.json';
L{end+1} = ['%   Canonical SHA-256  : ' defhash];
L{end+1} = '%   Parameter values   : models/literature_reference/parameters.json (Tables 1-2, locked, no refitting)';
L{end+1} = '%';
L{end+1} = '%   Regenerate with: addpath(''matlab/codegen'',''matlab/provenance''); generate_pure_literature_reference';
L{end+1} = '%   Hand edits are detected by test_codegen_and_provenance (regeneration sync test).';
L{end+1} = '%';
L{end+1} = '%   Literal deterministic translation of:';
L{end+1} = '%     Mavelli, F., Marangoni, R., Stano, P. (2015),';
L{end+1} = '%     "A Simple Protein Synthesis Model for the PURE System Operation",';
L{end+1} = '%     Bulletin of Mathematical Biology 77:1185-1212, DOI 10.1007/s11538-015-0082-8.';
L{end+1} = '%   Implemented: Sect. 2, Eqs. (5), (6), (8), (10), (12), (14), (20)-(27).';
L{end+1} = '%   NO equation was altered, added, or re-fitted (B1 literature benchmark).';
L{end+1} = '%';
L{end+1} = '%   State vector Y (concentrations in uM, time in s), fixed order:';
for k = 1:numel(states)
    L{end+1} = sprintf('%s', ['%     y(' num2str(states(k).index) ') ' ...
        pad(states(k).id, 5) ' : ' states(k).doc ' [uM]']);
end
L{end+1} = '%   DNA, TXcat, RScat, ENcat are FIXED inputs inside P, not states.';
L{end+1} = '%';
L{end+1} = '%   RATES (uM/s), fixed order:';
for k = 1:numel(rates)
    L{end+1} = sprintf('%s', ['%     rates(' num2str(rates(k).index) ') ' ...
        pad(rates(k).id, 9) ' : ' rates(k).doc '  [paper Eq. ' rates(k).paper_equation ']']);
end
L{end+1} = '%';
L{end+1} = ['%   NOTE (paper Sect. 2.3): each elongation event consumes two NTP' ...
            ' molecules; this two-fold factor appears in the stoichiometry of'];
L{end+1} = ['%   Eqs. (20)-(21) below, but the NTP dependence of V_TL remains a SINGLE' ...
            ' rectangular-hyperbolic factor. Do not replace it by NTP^2.'];
L{end+1} = '';
L{end+1} = 'NTP = y(1);  NXP = y(2);  nt = y(3);  A = y(4);';
L{end+1} = 'T = y(5);  AT = y(6);  a = y(7);  CP = y(8);';
L{end+1} = 'C = y(9);  TLcat = y(10);  % C and a appear in no rate law';
L{end+1} = '';
L{end+1} = '% ---- intermediates (canonical definition "intermediates") ----';
for k = 1:numel(inter)
    L{end+1} = sprintf('%s = %s;', inter(k).id, inter(k).codegen);
end
L{end+1} = '';
L{end+1} = '% ---- rate laws (paper equation numbers from the canonical definition) ----';
for k = 1:numel(rates)
    L{end+1} = sprintf('%s = %s;  %% Eq. %s', rates(k).id, rates(k).codegen, ...
        rates(k).paper_equation);
end
L{end+1} = '';
L{end+1} = 'rates = [V_TX, V_nt_deg, V_RS, V_TL, V_TL_deg, V_EN];';
L{end+1} = '';
L{end+1} = '% ---- ODEs (paper Eqs. (20)-(27); comments give the paper equation no.) ----';
L{end+1} = sprintf('dydt = zeros(%d,1);', numel(scg));
for k = 1:numel(scg)
    L{end+1} = sprintf('dydt(%d) = %s;  %% Eq. %s', scg(k).index, ...
        scg(k).codegen, scg(k).paper_ode);
end
L{end+1} = 'end';
text = strjoin(L, newline);

fid = fopen(outfile, 'w');
if fid == -1
    error('pure_ref:codegen:noWrite', 'cannot write %s', outfile);
end
fprintf(fid, '%s', text);
fclose(fid);

out = struct('file', outfile, 'sha256', pure_sha256_file(outfile), ...
    'definition_sha256', defhash, 'consistency_check', 'not_run');

% ---- stoichiometry consistency check (default path only) ----
if do_check
    clear('rhs_pure_literature_reference');
    rehash;
    p = pure_literature_reference_params();
    p.DNA = 0.0017;
    rng(20260918);
    y0 = p.y0';
    Y = [y0; 300*rand(5,10) + y0];   % y0 + 5 random perturbed states
    Smat = S.stoichiometry.matrix;
    divnames = S.stoichiometry.species_divisor;
    maxviol = 0;
    for i = 1:size(Y, 1)
        [dydt_gen, rates_gen] = rhs_pure_literature_reference(0, Y(i,:), p);
        R = rates_gen(:);
        for s = 1:numel(S.stoichiometry.species_order)
            dv = 1;
            spName = S.stoichiometry.species_order{s};
            if isfield(divnames, spName) && ~strcmp(divnames.(spName), '1')
                dv = p.(divnames.(spName));
            end
            expect = (Smat(s, :) * R) / dv;
            maxviol = max(maxviol, abs(expect - dydt_gen(s)));
        end
    end
    if maxviol > 1e-10
        error('pure_ref:codegen:stoichiometryMismatch', ...
            'state_codegen vs stoichiometry matrix violate to %.3e uM/s', maxviol);
    end
    out.consistency_check = sprintf('passed (max violation %.3e uM/s over %d states)', ...
        maxviol, size(Y, 1));
    fprintf('generated %s\n  definition sha256 = %s\n  consistency check: %s\n', ...
        outfile, defhash, out.consistency_check);
else
    fprintf('generated %s (consistency check skipped)\n', outfile);
end
end

function s = sortstruct(a, field)
vals = [a.(field)];
[~, ord] = sort(vals);
s = a(ord);
end

function t = pad(str, n)
t = str;
if length(t) < n; t = [t, blanks(n - length(t))]; end
end
