function m = pure_nondim_map(p)
%PURE_NONDIM_MAP Runtime form of the audited B1 scaling, derived only from P.
% State columns: [NTP NXP nt A T AT a CP C TLcat D_nt D_TLcat].
% Column state: y=x./m.state_scales; x=m.state_scales.*y.
% Row trajectories: Y=X./m.state_scales'; X=Y.*m.state_scales'.
% tau=m.k_nt_deg*t; t=tau/m.k_nt_deg; Vtilde=V/m.Vstar.
% certificate is descriptive metadata, never an independent parameter source.
expected = {'NTP','NXP','nt','A','T','AT','a','CP','C','TLcat'};
assert(isequal(p.state_names(:), expected(:)), 'pure_nondim:stateOrder', ...
    'The canonical physical state order must be preserved.');
validateattributes(p.y0, {'numeric'}, {'real','finite','numel',10,'nonnegative'});
validateattributes([p.n_NTP p.n_A p.n_T p.k_nt_deg p.L], ...
    {'numeric'}, {'real','finite','positive'});
validateattributes(p.DNA, {'numeric'}, {'real','finite','scalar','nonnegative'});
cN = p.y0(1); cA = p.y0(4); cT = p.y0(5);
cCP = p.y0(8); cTL = p.y0(10);
validateattributes([cN cA cT cCP cTL], {'numeric'}, {'positive'});
N = p.n_NTP*cN;
m.state_scales = [cN;N;N;cA;cT;cT;p.n_A*cA;cCP;cCP;cTL;N;cTL];
m.k_nt_deg = p.k_nt_deg;
m.Vstar = p.k_nt_deg*N;
g.fTA = p.n_T/p.n_A;
g.mu_TX = p.k_TX*p.TXcat/m.Vstar;
g.mu_RS = p.k_RS*p.RScat/m.Vstar;
g.mu_TL = p.k_TL*cTL/m.Vstar;
g.mu_EN = p.k_EN*p.ENcat/m.Vstar;
g.mu_TLdeg = p.k_TL_deg/p.k_nt_deg;
g.theta_DNA = p.DNA/(p.K_TX_DNA+p.DNA);
g.kappa_TX_NTP = p.K_TX_NTP/cN;
g.kappa_RS_A = p.K_RS_A/cA;
g.kappa_RS_T = p.K_RS_T/(g.fTA*cT);
g.kappa_RS_NTP = p.K_RS_NTP/cN;
g.kappa_TL_nt = p.K_TL_nt/N;
g.kappa_TL_AT = p.K_TL_AT/(g.fTA*cT);
g.kappa_TL_NTP = p.K_TL_NTP/cN;
g.kappa_EN_CP = p.K_EN_CP/cCP;
g.kappa_EN_NXP = p.K_EN_NXP/N;
g.rho_A = N/(p.n_A*cA);
g.rho_T = N/(p.n_T*cT);
g.rho_C = N/cCP;
% Only needed to express TLcat decay in the COMMON rate scale, not in its ODE.
g.TLcat_to_nucleotide_scale = cTL/N;
m.groups = g;
m.initial_dimensional = [p.y0(:);0;0];
m.initial_dimensionless = m.initial_dimensional./m.state_scales;
m.state_order = [expected, {'D_nt','D_TLcat'}];
m.rate_order = p.rate_names;

c.schema_version = '1.0';
c.model_id = p.meta.model_id;
c.source_model = 'models/literature_reference/model_definition.json';
c.authority = 'Derived mapping certificate; canonical model and parameter files remain scientific authority. Numeric snapshots are loaded reference values only.';
c.state_order = m.state_order;
c.dimensionless_state_order = arrayfun(@(i) sprintf('y%d',i),1:12,'UniformOutput',false);
c.scale_definitions = struct('c_NTP0','p.y0(1)','c_A0','p.y0(4)', ...
    'c_T0','p.y0(5)','c_CP0','p.y0(8)','c_TLcat0','p.y0(10)');
c.time = struct('dimensional','t','unit','s','dimensionless','tau', ...
    'forward','tau = k_nt_deg * t','inverse','t = tau / k_nt_deg', ...
    'scale_source','p.k_nt_deg','solver_independent_variable','tau');
expr = {'c_NTP0','n_NTP*c_NTP0','n_NTP*c_NTP0','c_A0','c_T0','c_T0', ...
    'n_A*c_A0','c_CP0','c_CP0','c_TLcat0','n_NTP*c_NTP0','c_TLcat0'};
for i = 1:12
    c.states(i) = struct('state',c.state_order{i}, ...
        'dimensionless',c.dimensionless_state_order{i},'dimensional_unit','uM', ...
        'scale_expression',expr{i}, ...
        'forward',sprintf('y%d = %s/(%s)',i,c.state_order{i},expr{i}), ...
        'inverse',sprintf('%s = (%s)*y%d',c.state_order{i},expr{i},i));
end
c.rate_scale = struct('symbol','Vstar','unit','uM/s', ...
    'expression','k_nt_deg*n_NTP*c_NTP0','forward','Vtilde = V/Vstar', ...
    'inverse','V = Vstar*Vtilde','rate_order',{p.rate_names}, ...
    'compact_main_rate_indices',[1 3 4 6], ...
    'nt_decay','Vtilde_nt_deg = y3', ...
    'TLcat_decay','Vtilde_TL_deg = mu_TLdeg*c_TLcat0/(n_NTP*c_NTP0)*y10', ...
    'dimensional_TLcat_decay','V_TL_deg = p.k_TL_deg*TLcat');
definitions = {'fTA','n_T/n_A'; 'mu_TX','k_TX*TXcat/Vstar'; ...
    'mu_RS','k_RS*RScat/Vstar'; 'mu_TL','k_TL*c_TLcat0/Vstar'; ...
    'mu_EN','k_EN*ENcat/Vstar'; 'mu_TLdeg','k_TL_deg/k_nt_deg'; ...
    'theta_DNA','DNA/(K_TX_DNA+DNA)'; 'kappa_TX_NTP','K_TX_NTP/c_NTP0'; ...
    'kappa_RS_A','K_RS_A/c_A0'; 'kappa_RS_T','K_RS_T/(fTA*c_T0)'; ...
    'kappa_RS_NTP','K_RS_NTP/c_NTP0'; 'kappa_TL_nt','K_TL_nt/(n_NTP*c_NTP0)'; ...
    'kappa_TL_AT','K_TL_AT/(fTA*c_T0)'; 'kappa_TL_NTP','K_TL_NTP/c_NTP0'; ...
    'kappa_EN_CP','K_EN_CP/c_CP0'; 'kappa_EN_NXP','K_EN_NXP/(n_NTP*c_NTP0)'; ...
    'rho_A','n_NTP*c_NTP0/(n_A*c_A0)'; 'rho_T','n_NTP*c_NTP0/(n_T*c_T0)'; ...
    'rho_C','n_NTP*c_NTP0/c_CP0'; ...
    'TLcat_to_nucleotide_scale','c_TLcat0/(n_NTP*c_NTP0)'};
c.dimensionless_group_definitions = cell2struct(definitions(:,2),definitions(:,1),1);
c.parameter_aliases = struct('C_TXcat','p.TXcat','C_RScat','p.RScat', ...
    'C_ENcat','p.ENcat','k_ntdeg','p.k_nt_deg','k_TLdeg','p.k_TL_deg');
c.observable_mappings = struct('mRNA','nt/(3*p.L) = n_NTP*c_NTP0*y3/(3*p.L)', ...
    'protein','a/p.L = n_A*c_A0*y7/p.L','unit','uM');
c.source_files = {'models/literature_reference/model_definition.json', ...
    'models/literature_reference/parameters.json','models/literature_reference/species.csv', ...
    'models/literature_reference/reactions.csv','matlab/generated/pure_literature_reference_params.m', ...
    'matlab/generated/rhs_pure_literature_reference.m', ...
    'matlab/src/simulate/simulate_pure_literature_reference.m', ...
    'models/literature_reference/dimensionless/derive_dimensionless.m', ...
    'models/literature_reference/dimensionless/dimensionless_result.txt', ...
    'models/literature_reference/dimensionless/README.md', ...
    'docs/audit/dimensionless_20260921/REPORT.md','docs/theory_notes.md'};
c.validation = struct('status','not_validated_by_builder', ...
    'scope','Mathematical/numerical equivalence of the frozen B1 deterministic representations only.');
m.certificate = c;
end
