function [dy, rates] = rhs_pure_literature_dimensionless(~, y, g)
%RHS_PURE_LITERATURE_DIMENSIONLESS Audited compact dy/dtau, independently coded.
% No dimensional RHS, inverse transform, clipping or parameter fitting here.
% rates uses canonical [TX nt_deg RS TL TL_deg EN] order, ALL divided by Vstar.
vTX = g.mu_TX*g.theta_DNA*y(1)/(g.kappa_TX_NTP+y(1));
vRS = g.mu_RS*y(4)/(g.kappa_RS_A+y(4)) ...
    *y(5)/(g.kappa_RS_T+y(5))*y(1)/(g.kappa_RS_NTP+y(1));
vTL = g.mu_TL*y(10)*y(3)/(g.kappa_TL_nt+y(3)) ...
    *y(6)/(g.kappa_TL_AT+y(6))*y(1)/(g.kappa_TL_NTP+y(1));
vEN = g.mu_EN*y(8)/(g.kappa_EN_CP+y(8))*y(2)/(g.kappa_EN_NXP+y(2));
dy = [-vTX-vRS-2*vTL+vEN; vRS+2*vTL-vEN; vTX-y(3); ...
    -g.rho_A*vRS; g.rho_T*(-vRS+vTL); g.rho_T*(vRS-vTL); ...
    g.rho_A*vTL; -g.rho_C*vEN; g.rho_C*vEN; ...
    -g.mu_TLdeg*y(10); y(3); g.mu_TLdeg*y(10)];
rates = [vTX, y(3), vRS, vTL, ...
    g.mu_TLdeg*g.TLcat_to_nucleotide_scale*y(10), vEN];
end
