function c = export_pure_nondim_map(destination, sourceCommit)
%EXPORT_PURE_NONDIM_MAP Derived certificate from the existing runtime builder.
% Empty destination builds without writing. Numeric values have no authority
% independent of the canonical loader. DNA-dependent theta is kept separate.
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'matlab','generated'),fullfile(root,'matlab','src','theory'), ...
    fullfile(root,'matlab','src','provenance'));
if nargin < 1, destination = ''; end
if nargin < 2, sourceCommit = pure_git_state(root).commit; end
criteriaPath = 'docs/audit/nondimensionalization_validation_v2_20260923/acceptance_criteria.json';
criteria = jsondecode(fileread(fullfile(root,criteriaPath)));
p = pure_literature_reference_params(); p.DNA = criteria.DNA_uM(1);
m = pure_nondim_map(p); idx = [1 3 4 6 8 10];
c.schema_version = '2.0'; c.model = p.meta.model_id;
c.validation_version = 'v2'; c.validation_criteria = criteriaPath;
historicalPath = 'docs/audit/nondimensionalization_validation_20260923/validation_results.json';
historical = jsondecode(fileread(fullfile(root,historicalPath)));
c.historical_v1_status = historical.overall;
c.historical_v1_reason = 'Composite derivative/reconstruction floating-point gate';
c.historical_v1_evidence = historicalPath;
c.scientific_source = struct('model','models/literature_reference/model_definition.json', ...
    'parameters','models/literature_reference/parameters.json', ...
    'loader','matlab/generated/pure_literature_reference_params.m', ...
    'computation','matlab/src/theory/pure_nondim_map.m', ...
    'authority','Derived certificate only; canonical sources retain scientific authority.');
c.generated_from_commit = sourceCommit;
c.time = struct('dimensional_variable','t','dimensionless_variable','tau', ...
    'dimensional_unit','s','scale_s',1/m.k_nt_deg,'k_nt_deg_per_s',m.k_nt_deg, ...
    'rate_constant_source','p.k_nt_deg','forward_relation','tau=k_nt_deg*t', ...
    'inverse_relation','t=tau/k_nt_deg');
c.reduced_coordinates = struct('dimensional_order',{m.state_order(idx)}, ...
    'full_state_indices_1_based',idx, ...
    'dimensionless_order',{{'y1','y3','y4','y6','y8','y10'}}, ...
    'scales_uM',m.state_scales(idx)');
c.full_state_order = m.state_order;
c.state_scales = struct('unit','uM','values',m.state_scales', ...
    'definitions',m.certificate.states);
c.rate = m.certificate.rate_scale; c.rate.V_star_uM_per_s = m.Vstar;
c.dimensionless_parameters.constant = rmfield(m.groups,'theta_DNA');
c.dimensionless_parameters.definitions = m.certificate.dimensionless_group_definitions;
for k = 1:numel(criteria.DNA_uM)
    p.DNA = criteria.DNA_uM(k); mk = pure_nondim_map(p);
    c.dimensionless_parameters.input_dependent(k) = struct( ...
        'DNA_uM',p.DNA,'theta_DNA',mk.groups.theta_DNA);
end
c.validation_conditions = criteria;
c.invariants = struct('order',{{'I_NTP','I_AA','I_tRNA','I_CP','I_TLcat','I6'}}, ...
    'initial_values',pure_dimensionless_invariants(m.initial_dimensionless,m)', ...
    'definitions',{{'y1+y2+y3+y11','(y4+y7)/rho_A+y6/rho_T', ...
    'y5+y6','y8+y9','y10+y12','y2+y9/rho_C-3*y7/rho_A-y6/rho_T'}});
c.initial_dimensionless_state = m.initial_dimensionless';
c.forward_transform = struct('full','y=x./state_scales', ...
    'reduced','q=z./reduced_scales','time','tau=k_nt_deg*t');
c.inverse_transform = struct('full','x=state_scales.*y', ...
    'reduced','z=reduced_scales.*q','time','t=tau/k_nt_deg', ...
    'reconstruction_order',{{'y5','y7','y9','y2','y12','y11'}}, ...
    'reconstruction',{{'I_tRNA-y6','rho_A*I_AA-y4-(rho_A/rho_T)*y6', ...
    'I_CP-y8','I6-y9/rho_C+3*y7/rho_A+y6/rho_T', ...
    'I_TLcat-y10','I_NTP-y1-y2-y3'}});
c.observable_mappings = m.certificate.observable_mappings;
c.validation_evidence = 'docs/audit/nondimensionalization_validation_v2_20260923/validation_results.json';
paths = {c.scientific_source.model,c.scientific_source.parameters, ...
    c.scientific_source.loader,c.scientific_source.computation, ...
    'matlab/generated/rhs_pure_literature_reference.m', ...
    'matlab/src/theory/pure_dimensionless_invariants.m', ...
    'matlab/src/theory/reconstruct_pure_exact_reduced_nondim_state.m', ...
    'matlab/src/theory/rhs_pure_exact_reduced_nondim.m', ...
    'matlab/src/theory/simulate_pure_exact_reduced_nondim.m', ...
    'scripts/export_pure_nondim_map.m',criteriaPath,historicalPath};
for k = 1:numel(paths)
    c.source_fingerprints(k) = struct('path',paths{k}, ...
        'sha256',pure_sha256_file(fullfile(root,paths{k})));
end
if ~isempty(destination)
    fid = fopen(destination,'w','n','UTF-8'); assert(fid>=0);
    closeFile = onCleanup(@() fclose(fid));
    fprintf(fid,'%s\n',jsonencode(c,'PrettyPrint',true));
end
end
