function record = export_rs_qssa_parameters()
%EXPORT_RS_QSSA_PARAMETERS Derived metadata; canonical loader remains authority.
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root,'matlab','generated'),fullfile(root,'matlab','src','theory'), ...
    fullfile(root,'matlab','src','provenance'));
p = pure_literature_reference_params(); p.DNA = 0.00034;
q = rs_reduction_parameters(p);
record = struct('schema_version','1.0','model_id','PURE_RS_QSSA_synthetic_fast_ref', ...
    'source_type',q.source_type,'evidence_level',q.evidence_level, ...
    'input_commit','c2bb0ae63ba106d4f51bf2182dfd28dfe187e743');
record.construction = struct('method',q.construction_method, ...
    'phi_alpha',q.phi_alpha,'phi_beta',q.phi_beta,'phi_gamma',q.phi_gamma, ...
    'D_ref','V_RS_ref/(E_T*phi_alpha*phi_gamma)', ...
    'alpha_ref','phi_alpha*D_ref','beta_ref','phi_beta*D_ref', ...
    'gamma_ref','phi_gamma*D_ref','k1','alpha_ref/(A0*NTP0)', ...
    'kminus1','beta_ref','k2','gamma_ref/T_eff0', ...
    'interpretation','Synthetic local matching only; no fit and no all-state-domain Eq.8 identity');
record.reference_state = struct('state_order',{p.state_names},'y0',p.y0', ...
    'DNA_uM',p.DNA,'fTA',p.n_T/p.n_A,'T_eff0',q.T_eff_ref, ...
    'E_T',p.RScat,'V_RS_ref',q.V_RS_ref,'M_qss0',q.M_qss_ref, ...
    'D_ref',q.D_ref,'alpha_ref',q.alpha_ref,'beta_ref',q.beta_ref, ...
    'gamma_ref',q.gamma_ref,'tau_M_ref',q.tau_M_ref);
for name = {'k1','kminus1','k2'}
    key = name{1};
    record.parameters.(key) = struct('value',q.(key),'unit',q.units.(key), ...
        'source_type',q.source_type);
end
record.mapping = struct('ATP_RS','canonical NTP bookkeeping, not ATP-specific chemistry', ...
    'T_eff','(p.n_T/p.n_A)*T','E_T','p.RScat','PPi','No state; effect lumped into kminus1');
record.source_review = struct('exact_surrogate_microconstants_found',false, ...
    'primary_source','Mavelli et al. 2015 DOI 10.1007/s11538-015-0082-8; normalized PDF pages 7-8 and 13', ...
    'finding','Eq.8 and Table2 give apparent k_RS and Michaelis constants, not k1/kminus1/k2 of this two-step surrogate', ...
    'excluded','Unrelated aaRS numbers and generic enzyme fixtures cannot supply exact surrogate provenance', ...
    'extracted_text_note','Existing provenance ledger text hash is stale; verified PDF and current text fingerprints below; historical bytes unchanged');
paths = {'models/literature_reference/parameters.json', ...
    'models/literature_reference/model_definition.json', ...
    'models/literature_reference/model_manifest.json', ...
    'matlab/generated/rhs_pure_literature_reference.m', ...
    'matlab/generated/pure_literature_reference_params.m', ...
    'references/R01_Mavelli2015/A_Simple_Protein_Synthesis_Model_PURE_normalized.pdf', ...
    'references/R01_Mavelli2015/A_Simple_Protein_Synthesis_Model_PURE.md'};
for i = 1:numel(paths)
    record.source_fingerprints(i) = struct('path',paths{i}, ...
        'sha256',pure_sha256_file(fullfile(root,paths{i})));
end
outdir = fullfile(root,'models','reductions','rs_qssa');
if ~exist(outdir,'dir'); mkdir(outdir); end
fid = fopen(fullfile(outdir,'parameters.json'),'w','n','UTF-8');
assert(fid>=0); cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(record,'PrettyPrint',true));
end
