"""R5 evidence navigation, descriptive closeout and output bindings."""
from r5_common_v1 import *
import subprocess,sys
def main():
 if '--seal-verification' in sys.argv:
  paths=[OUT/'verification.json',OUT/'manifest.json']+[p for p in OUT.rglob('*') if p.is_file() and ('independent_' in p.name or p.name=='critical_manifold_verification.json')]
  write_json(OUT/'verification_binding.json',{p.relative_to(ROOT).as_posix():sha(p) for p in sorted(paths)});print('Verifier outputs sealed');return
 checked_registration();ck=json.loads((OUT/'ck/structure_summary.json').read_text());scan=json.loads((OUT/'ck/eta_scan_summary.json').read_text());gly=json.loads((OUT/'glyrs/summary.json').read_text());balance=json.loads((OUT/'balance/balance_decomposition_summary.json').read_text())
 # Exact source paths used, with transitive source/runtime dependencies covered
 # additionally by the immutable complete pre-R5 snapshot.
 from r4_fast_block_common_v1 import REG,historical_path
 used=[]
 for c in REG['conditions']:
  name=c['condition_id'];used.extend([historical_path(name)/'full_state.npz',historical_path(name)/'directed_ledgers.npz'])
  for family in ['glyrs_only','metrs_only']:
   p=ROOT/'results/reduction/r4_fast_block_screen'/family/name
   used.extend(f for f in p.iterdir() if f.is_file() and (f.suffix=='.npz' or f.name in ['result.json','manifold_geometry.csv']))
  p=ROOT/'results/reduction/r4_fast_block_screen/source_uncertainty'/name;used.extend(f for f in p.iterdir() if f.is_file())
 used.extend([ROOT/'models/pnas2017_full_reference/original/fMGG_synthesis.xml',ROOT/'models/pnas2017_full_reference/normalized/fMGG_synthesis_constant_stoichiometry.xml',ROOT/'results/pnas2017_reference/rr_cvode_author_csv_20260924/effective_author_conditions.xml'])
 used.extend((ROOT/'models/pnas2017_full_reference/original/simulate/Simulate_fMGG_synthesis/dat').glob('*.csv'))
 used.extend([ROOT/p for p in ['models/pnas2017_full_reference/audit/reactions.csv','models/pnas2017_full_reference/audit/reaction_balance_audit.csv','docs/reduction/source_coordinate_certificate_v4.json','docs/reduction/conservation_laws_v0.csv','docs/reduction/r4_fast_block_candidates_v1.json','docs/reduction/r3_carrier_chart_v1.json','docs/audit/pnas2017_aminoacylation_reduction_v1/binit_v1r2_matrix.csv','results/reduction/r4_fast_block_screen/source_reuse_verification.json']])
 write_json(OUT/'used_inputs.json',{p.relative_to(ROOT).as_posix():sha(p) for p in sorted(set(used))})
 scientific={'CK':['CK_FAST_SUBSYSTEM_STRUCTURE_VERIFIED','CK_CRITICAL_MANIFOLD_ANALYTICALLY_DEFINED','CK_FAST_LAYER_ATTRACTING_ON_TESTED_DOMAIN',scan['status'],'CK_ETA1_ACCURACY_DESCRIPTIVE' if scan.get('eta1_descriptive_test_executed') else 'CK_ETA1_TEST_NOT_EXECUTED','CK_REDUCTION_NOT_YET_PROMOTED'],'GlyRS':gly['classification'],'balance':balance['classification']}
 # Conservative next human decision: source/ledger attribution remains unresolved
 # and the reconstructed full-state accounting policy requires explicit repair.
 recommendation='FIX_BALANCE_ACCOUNTING_BEFORE_ANY_NEW_REDUCTION'
 questions=[{'question':'Is CK partial-equilibrium singular limit mathematically coherent?','answer':'Yes for the declared binding subsystem and physical frozen-total domain; full-PURE uniform theorem hypotheses remain open.','evidence':'ck/structure_summary.json; CK theory derivations'}, {'question':'Does error decrease as eta tends to zero?','answer':scan['status'],'evidence':'ck/singular_eta_scan.csv'}, {'question':'Is eta=1 accurate enough to justify formal broader validation?','answer':'No promotion decision. Baseline state and slow-total accuracy is descriptive; numerical budgets, flux reconstruction and broader conditions require human review.','evidence':'ck/baseline_original_parameter_comparison.csv'}, {'question':'Does feedback-aware GlyRS predictor substantially improve R4 lag explanation?','answer':str(gly['improved_conditions'])+'/9 improve; baseline approximately halves error, high GlyRS strongly improves, low GlyRS and low tRNA worsen. Local feedback does not explain every condition.','evidence':'glyrs/condition_predictor_comparison.csv'}, {'question':'Is R4 balance uncertainty mostly ledger numerics or a real reduced accounting problem?','answer':'Tight-ledger sensitivity exceeds summation-only changes, with no exact-law failure observed. Full reconstructed ledgers require algebraic redistribution. State/dense/extent attribution remains mixed/unresolved.','evidence':'balance/balance_decomposition_summary.json; reconstructed_full_state_accounting.csv'}]
 write_json(OUT/'decision_table.json',{'questions':questions,'recommendation':recommendation,'role':'EVIDENCE_FOR_HUMAN_REVIEW_ONLY','next_stage_executed':False,'scientific_status':scientific})
 # Derived graph is structured navigation, not authoritative evidence.
 inputs=json.loads((OUT/'used_inputs.json').read_text());nodes=[];edges=[]
 for track in ['ck','glyrs','balance']:
  for p in sorted((OUT/track).glob('*')):
   if p.is_file():nodes.append({'id':p.relative_to(ROOT).as_posix(),'track':track,'type':'DERIVED_EVIDENCE','confidence':'EXTRACTED','sha256':sha(p),'freshness':'CURRENT_R5_RUN'})
 for p,h in inputs.items():nodes.append({'id':p,'type':'SOURCE_OR_FROZEN_EVIDENCE','confidence':'EXTRACTED','sha256':h,'freshness':'FROZEN_PRE_R5_SNAPSHOT'})
 for track in ['ck','glyrs','balance']:
  claim='R5_'+track.upper();nodes.append({'id':claim,'type':'INTERPRETATION','confidence':'INFERRED','status':scientific['CK' if track=='ck' else 'GlyRS' if track=='glyrs' else 'balance']})
  for n in nodes:
   if n.get('track')==track:edges.append({'source':n['id'],'target':claim,'relation':'SUPPORTS_DESCRIPTIVE_INTERPRETATION','confidence':'INFERRED'})
 edges.extend({'source':p,'target':'R5_GLYRS' if 'glyrs' in p else 'R5_BALANCE' if 'ledgers' in p or 'uncertainty' in p else 'R5_CK','relation':'USED_SOURCE_EVIDENCE','confidence':'EXTRACTED'} for p in inputs)
 write_json(OUT/'evidence_navigation.json',{'derived_navigation_only':True,'source_authority_not_replaced':True,'ambiguity':'absolute units and separated historical numerical errors remain AMBIGUOUS','nodes':nodes,'edges':edges})
 doc='# R5 mechanism-first summary — 2026-10-07\n\nParent main: `0b6f9ad649a7e283e440e0294a021123551f6858`. Execution parent: local R4 `9def91d` (registration `88c0bfa`), which was not on origin/main. Isolated branch `codex/r5-mechanism-first-20261007`. No merge, push, fitting, reaction deletion, threshold change or next-stage execution.\n\nCanonical four CK binding reactions agree with author parameters 2/1000/2/1000, K0=K1=500 in the inferred reference concentration convention. Sf rank2; full left-null basis rank239, restriction to R1 class rank212. T0,T1,B are fast invariants and dynamic totals, not global constants. Hprime>0 yields unique p∈[0,B]; qi=Ti p/(500+p). Equal-rate Jacobian eigenvalues are −(2p+1000) and −(2p+1000+2(CK+CK_ADP)). Fast layer attracts on physical frozen domain. Across1809 frozen source samples, max equilibrium relaxation is '+format(ck['max_tau_s'],'.12g')+' seconds; no sampled loss of normal hyperbolicity.\n\nCK scan/initial layer:\n\n```json\n'+json.dumps(scan,indent=2)+'\n```\n\nInitial layer and startup rule are explicit in ck/initial_layer_definition.json and initial_layer_comparison.csv. Earlier arithmetic/coordinate attempts, their failures, checkpoints and computational stops remain retained. They are UNSCORED. The final chart prioritizes R1 retained coordinates and uses centered totals plus accurate row sums; parameters, tolerances, eta sequence and switch rule remain fixed. See r5_ck_runtime_qualification_v1.md. No source trajectory is clipped or projected.\n\nGlyRS:\n\n```json\n'+json.dumps(gly,indent=2)+'\n```\n\nAperp=Gq−Dh Fq is feedback-aware; measured ratios and nonnormality diagnostics are retained. Predictors are diagnostics, not an h1 model or rigorous error bound.\n\nBalance:\n\n```json\n'+json.dumps(balance,indent=2)+'\n```\n\n27 exact law drifts are separate from directed ledger and reconstructed algebraic-state residuals. High-accuracy summation changes diagnostics only. Full state/dense/extent attribution is unresolved; no historical R4 gate or classification is altered.\n\n| Human question | Evidence-based answer |\n|---|---|\n'
 for q in questions:doc+='|'+q['question']+'|'+q['answer']+'|\n'
 doc+='\nExactly one next human recommendation: **'+recommendation+'**. This is evidence for review only; stop before next stage. CK remains NOT_YET_PROMOTED and PURE_reduced_core remains NOT_VALIDATED.\n\nIndependent verification: see results/reduction/r5_mechanism_first/verification.json for the measured result. Its PASS, if obtained, establishes engineering/provenance checks only. All2420 pre-R5 files are individually byte-hash checked; new outputs are SHA-256 bound by manifest.json and verifier outputs by verification_binding.json. The evidence_navigation.json graph is derived navigation only. Complete requested documentation, CSVs, retained solver arrays and scripts are in the registered tree; original absolute unit metadata and full-PURE uniform bounds remain unresolved.\n'
 write_doc('r5_mechanism_first_summary.md',doc)
 paths=list(OUT.rglob('*'))+list(DOC.glob('r5*.md'))+[DOC/'r5_theory_scope_v1.json',ROOT/'docs/theory/qssa_singular_perturbation_guidance.md']+list((ROOT/'scripts').glob('*r5*v1.py'))
 excluded={'manifest.json','verification.json','verification_binding.json','critical_manifold_verification.json'}
 files={p.relative_to(ROOT).as_posix():sha(p) for p in sorted(set(paths)) if p.is_file() and p.name not in excluded and 'independent_' not in p.name and 'verification_attempts' not in p.parts}
 write_json(OUT/'manifest.json',{'schema':'R5_MECHANISM_FIRST_MANIFEST_V1','parent_main_sha':'0b6f9ad649a7e283e440e0294a021123551f6858','execution_parent_sha':'9def91d','scientific_status':scientific,'files_sha256':files,'independent_verifier_outputs':'Separately sealed by verification_binding.json to avoid self-hash cycles','preexisting_files_snapshot':'historical_snapshot.json','all_micro_gross_ledgers_preserved_claim':False,'promotion':False,'recommendation':recommendation})
 print('Manifest',len(files),'files; recommendation',recommendation,flush=True)
if __name__=='__main__':main()
