"""Canonical CK provenance, exact fast structure, and existing-domain stability."""
from r5_ck_partial_equilibrium_runtime_v1 import *
from verify_reduction_audit_v0 import SOURCE,AUTHOR,rows
def main():
 checked_registration();r=CKRuntime();s=r.source;dest=OUT/'ck'
 inventory={v['reaction_id']:v for v in rows(ROOT/'models/pnas2017_full_reference/audit/reactions.csv')}
 records=[];forcing=[]
 for j,re in enumerate(s.reactions):
  if not set(NAMES)&(set(re['reactants'])|set(re['products'])):continue
  selected=j in r.fast
  records.append({'reaction_id':re['id'],'declared_fast':selected,'reactants':json.dumps({n:str(v) for n,v in re['reactants'].items()}),'products':json.dumps({n:str(v) for n,v in re['products'].items()}),'stoichiometry':json.dumps({s.species[i]:str(v) for i,v in s.stoich[j].items()}),'source_subsystem':inventory[re['id']]['source_module_ids'],'original_source_reaction_id':inventory[re['id']]['source_module_reaction_refs_json'],'author_parameter_id':re['id']+'_k1','author_parameter_value':str(re['k']),'units':'reference concentration^-1 s^-1 (binding) or s^-1 (unimolecular); uM inference, metadata unresolved','canonical_rate_law':inventory[re['id']]['kinetic_law_formula'],'source_hash':sha(SOURCE),'parameter_csv_hash':sha(AUTHOR/'fMGG_synthesis_parameters.csv')})
  if not selected:
   c=np.asarray(r.T[:3]@r.S[:,j]).ravel()
   forcing.append({'reaction_id':re['id'],'dT0_per_event':c[0],'dT1_per_event':c[1],'dB_per_event':c[2],'retained_as_slow':True})
 write_csv(dest/'reaction_definition.csv',records);write_csv(dest/'slow_forcing_of_fast_totals.csv',forcing)
 write_csv(dest/'fast_left_nullspace.csv',[{'row':i,'label':['T0','T1','B'][i] if i<3 else 'unchanged_'+s.species[int(np.flatnonzero(row)[0])],'species_coefficients_json':json.dumps({s.species[j]:int(row[j]) for j in np.flatnonzero(row)}),'scope':'FAST_SUBSYSTEM_INVARIANT;DYNAMIC_TOTAL_COORDINATE'} for i,row in enumerate(r.Lf)])
 np.savez_compressed(dest/'coordinate_map.npz',Sf=r.S[:,r.fast].toarray(),Lf=r.Lf,T=r.T,Xz=r.Xz,D=r.D,W=r.W,selected=r.selected)
 from r4_fast_block_common_v1 import REG,source_data
 st=[]
 for c in REG['conditions']:
  t,full=source_data(c['condition_id'])
  for i,x in enumerate(full):
   totals=r.T[:3]@x;p,q=material_root(*totals);a=2*p+1000;e1=-a;e2=-a-2*((totals[0]-q[0])+(totals[1]-q[1]));ev=np.sort(np.linalg.eigvals(fast_jac(q,totals)).real)
   rawp=x[s.index['CP']];rawq=x[r.qix];rawa=2*rawp+1000;rawe2=-rawa-2*(x[s.index['CK']]+x[s.index['CK_ADP']]);rawev=np.sort(np.linalg.eigvals(fast_jac(rawq,totals)).real)
   st.append({'condition':c['condition_id'],'sample_index':i,'time_s':t[i],'T0':totals[0],'T1':totals[1],'B':totals[2],'p_equilibrium':p,'q0':q[0],'q1':q[1],'lambda1_s_inverse':e1,'lambda2_s_inverse':e2,'tau_fast_s':1/a,'minimum_abs_real':a,'analytic_eigenvalue_error':float(max(abs(ev-np.sort([e1,e2])))),'raw_source_lambda1_s_inverse':-rawa,'raw_source_lambda2_s_inverse':rawe2,'raw_source_tau_s':1/rawa,'raw_source_analytic_eigenvalue_error':float(max(abs(rawev-np.sort([-rawa,rawe2]))))})
 write_csv(dest/'fast_layer_stability.csv',st)
 sm={'rank_Sf':2,'reaction_nullity':2,'left_nullity_full':239,'left_nullity_R1_class':212,'selected':FAST_IDS,'K0':500,'K1':500,'parameter_values':[2,1000,2,1000],'max_tau_s':max(v['tau_fast_s'] for v in st),'min_abs_real':min(v['minimum_abs_real'] for v in st),'samples':len(st),'conditions':9,'source_sha256':sha(SOURCE),'units_status':'INFERRED_REFERENCE_CONVENTION_NOT_AUTHORITATIVE_SBML_UNITS','physical_normal_hyperbolicity_proof':'equal-rate eigenvalues <= -1000 throughout physical frozen-total domain'}
 write_json(dest/'structure_summary.json',sm)
 sm['max_raw_source_tau_s']=max(v['raw_source_tau_s'] for v in st);sm['min_raw_source_abs_real']=min(-v['raw_source_lambda1_s_inverse'] for v in st);write_json(dest/'structure_summary.json',sm)
 write_doc('r5_ck_fast_reaction_definition_v1.md','# CK declared fast reactions\n\nExactly re0000000332/333: CK+CP ⇌ CK_CP; re0000000336/337: CK_ADP+CP ⇌ CK_CP_ADP. Canonical table, SBML and author CSV agree: k_on=2, k_off=1000 for each pair. K0=K1=500 in reference concentration scale. All '+str(len(records)-4)+' other touching reactions are listed in reaction_definition.csv and retained as slow forcing. Original module IDs, rate laws, stoichiometry and hashes are in that table.\n\nAuthor CSV omits units; docs/pnas2017/chemical_ledger.md supports µM inference from 50mM CP ↔ 50000. docs/pnas2017/sbml_audit.md documents incomplete metadata. Numerical time uses repository seconds convention. These interpretations do not repair the absolute biochemical unit audit.')
 write_doc('r5_ck_fast_invariants_v1.md','# CK fast invariants\n\nSpecies order (CK,CK_ADP,CP,CK_CP,CK_CP_ADP), columns (332,333,336,337):\n\n```\nSf=[[-1,1,0,0],[0,0,-1,1],[-1,1,-1,1],[1,-1,0,0],[0,0,1,-1]]\nLf_local=[[1,0,0,1,0],[0,1,0,0,1],[0,0,1,1,1]]\n```\n\nrank=2; reaction nullity=2; local left-nullity=3. Append the 236 unaffected-species identity rows to obtain full-row-rank Lf (239×241), Lf Sf=0 exactly. Thus T0=CK+CK_CP, T1=CK_ADP+CK_CP_ADP, B=CP+CK_CP+CK_CP_ADP. All are FAST_SUBSYSTEM_INVARIANT and DYNAMIC_TOTAL_COORDINATE, never SOURCE_GENERAL_EXACT_CONSERVATION. slow_forcing_of_fast_totals.csv gives every touching non-fast column and coefficients. These totals change in the full model. Restricting Lf to the exact R1 SOURCE_GENERAL 214-dimensional class gives rank212; selected coordinate rows include all three totals. The 27 source-general laws are retained via the affine R1 lift, not asserted for fast totals.')
 write_doc('r5_ck_critical_manifold_derivation_v1.md','# CK critical manifold and physical uniqueness\n\nWith CK=T0-q0, CK_ADP=T1-q1, p=B-q0-q1, each binding equilibrium gives qi=Ti p/(Ki+p). H=p+T0 p/(K0+p)+T1 p/(K1+p)-B. For nonnegative totals and positive Ki, H(0)=-B≤0, H(B)≥0 and Hprime=1+T0 K0/(K0+p)^2+T1 K1/(K1+p)^2>0 for p≥0. Intermediate value plus strict monotonicity proves unique p∈[0,B], including p=0 when B=0; then 0≤qi≤Ti. This is an analytical existence/uniqueness result, not a multistart claim. Equal K reduces to p²+(K+T0+T1-B)p-BK=0; the runtime uses its cancellation-resistant positive root. Numerical direct equation solves and derivatives are independently checked.')
 write_doc('r5_ck_fast_layer_stability_v1.md','# CK frozen fast layer\n\nqdot_i=ki_on p(Ti-qi)-ki_off qi, p=B-q0-q1. Jii=-ki_on(p+Ti-qi)-ki_off; Jij=-ki_on(Ti-qi), i≠j. Equal rates give J=-a I-k_on u 1T, a=k_on p+k_off, u=(T0-q0,T1-q1). Eigenvalues -a and -a-k_on(u0+u1). In the physical frozen-total domain these are ≤-1000 s^-1, hence local attractivity and no loss of normal hyperbolicity. The feasible triangle qi≥0, qi≤Ti, sum qi≤B is forward invariant. Q=q0+q1 solves Qdot=k_on(B-Q)(T0+T1-Q)-k_off Q, strictly decreasing RHS derivative on its physical interval, with unique attracting root. At converged Q, the splitting equations are contracting linear equations. This proves global convergence for this equal-rate frozen subsystem, including degenerate zero totals by continuous extension. It does not prove full-PURE Fenichel validity or eta=1 accuracy.\n\nExisting nine-condition domain: '+str(sm['samples'])+' samples; worst equilibrium relaxation '+format(sm['max_tau_s'],'.12g')+' s, min |Re λ|='+format(sm['min_abs_real'],'.12g')+' s^-1. Per-condition/time eigenvalues and analytic/numeric differences are in fast_layer_stability.csv.')
 write_doc('r5_ck_singular_family_v1.md','# CK singular family\n\nx_dot=S_s v_s(x)+eta^-1 S_f v_f_star(x). Only the four declared directed rate constants divide by dimensionless eta; Kd remains exactly 500, and each full stoichiometric column acts on every involved species. All other kinetics and all source files are unchanged. On fast time tau=t/eta, z_tau=eta Lf S_s v_s, q_tau=g(z,q)+eta slow_q_forcing. eta→0 freezes fast totals and other fast invariants. eta=1 alone is original physical parameter point; other values are theory-only. No eta parameters are written to canonical CSV.')
 write_doc('r5_ck_reduced_slow_flow_derivation_v1.md','# CK projected slow flow and observability\n\nFull fast-invariant map Lf has 239 rows. Within R1 SOURCE_GENERAL class select a rank212 map T from Lf. Append physical fast coordinates q=(CK_CP,CK_CP_ADP); W=[T L_R1; E_q L_R1] is invertible (214×214). The affine reconstruction x=c+Xz z+D q retains all27 exact source laws; T D=0 and T Xz=I. Phi(z)=c+Xz z+D h(z) with h defined by the physical material root. Derive zdot=T S_s v_s(Phi(z)); no source ODE row is deleted. TSf=0; all964 slow columns remain. Four declared fast gross reaction records remain provenance-visible.\n\nFull state reconstruction has 212 dynamic coordinates and two equilibrium coordinates, within the same source-general class. No source trajectory is projected. Initial outer state Phi(Tx0) carries a disclosed fast jump; hybrid retains startup.\n\nMICROSCOPIC_GROSS_FLUXES: A leading equilibrium gross rates are k_on p CK = k_off q (scaled by eta^-1 only for the theory family). B required signed slow net redistribution is n=Dh F-(S_s v_s)_q; this follows from qdot=Dh F, and its complete action is S_forward n. With full derivative of g at frozen totals, a first-order manifold offset solves J_fast h1=Dh F-(S_s v_s)_q, so q=h0+eta h1 yields finite pair-net n. This is a derived reconstruction policy, not an implemented higher-order state model. C exact source gross directed extents require source integration; leading equilibrium ledgers need not match them. No claim that all968 microscopic ledgers are preserved. State, fast-state and gross-flux classes are reported separately.')
 print(json.dumps(sm),flush=True)
if __name__=='__main__':main()
