"""Additive successor documents and provenance-aware structured navigation."""
from r5_common_v1 import ROOT, write_json, write_csv, write_doc, sha
import json, csv
OUT=ROOT/'results/reduction/r5c_corrigendum'

def main():
    gate=json.loads((OUT/'r4_gate_summary.json').read_text()); ck=json.loads((OUT/'ck_fast_current_summary.json').read_text())
    eta=json.loads((ROOT/'results/reduction/r5_mechanism_first/ck/eta_scan_summary.json').read_text())
    balance=json.loads((ROOT/'results/reduction/r5_mechanism_first/balance/balance_decomposition_summary.json').read_text())
    issues=[
      ('C1','Global fastest same-dimensional alignment as a necessary QSSA gate','Global Schur/CSP alignment is SUPPORTING_GEOMETRIC_DIAGNOSTIC, not NECESSARY_QSSA_ACCEPTANCE_GATE.','docs/reduction/r4_mixed_csp_mode_diagnostic.md','No fixed four-species map justified; nonlinear/moving manifold existence remains open.'),
      ('C2','Apparently fast species imply their derivatives should be set to zero','FAST_REACTION_PROCESS_FIRST: derive fast invariants, singular limit, critical manifold and projected slow flow.','docs/reduction/r5_ck_fast_reaction_definition_v1.md','CK binding directions are fast; CK bound species also participate in slower chemistry.'),
      ('C3','Large startup fast-state error alone rejects the outer QSSA','Separate FULL_WINDOW, POST_INITIAL_LAYER and COMPOSITE_OR_HYBRID.','results/reduction/r5_mechanism_first/ck/initial_layer_definition.json','CK startup mismatch does not reject the outer limit; verified R4 post-layer errors remain too large.'),
      ('C4','Overall NUMERICALLY_UNRESOLVED prevents any logically decisive screen fail','A resolved mandatory fail excludes passing all gates while other metrics remain unresolved.','results/reduction/r4_fast_block_screen/glyrs_only/R3_BASE/derived_review_result.json','Historical overall status unchanged; new uncertainty-aware gate audit is decisive.'),
      ('C5','Unresolved balance makes the family screen outcome undecidable','BOTH_FAMILY_CANDIDATES_FAIL_REGISTERED_GATE_SCREEN; combined-block causal explanation UNDETERMINED.','docs/reduction/r4_fast_block_summary.md','Family screen failure does not establish independent defects or exclude shared-resource causality.'),
      ('C6','R3/R4 failure implies all aminoacylation/QSSA/partial equilibrium is impossible','Only tested zero-order 21-, 9- and 12-state graphs fail the registered requirements on the tested domain.','docs/reduction/human_r3_successor_provenance_20261007.md','H5 semantics preserved. CK is a methodological counterexample, not proof of aminoacylation reducibility.'),
      ('C7','Exact conservation and directed extent closure are the same test','Separate exact-law drift, directed ledger residual, slow balance and algebraic full reconstruction.','results/reduction/r5_mechanism_first/balance/balance_decomposition_summary.json','No observed exact-law failure; state/dense/extent attribution remains MIXED / UNRESOLVED.'),
      ('C8','Accurate rapid-equilibrium states guarantee accurate gross microscopic fluxes','State convergence does not imply equally conditioned gross directed extent convergence.','docs/reduction/r5_ck_reduced_slow_flow_derivation_v1.md','Large eta^-1 opposing turnover can cancel to a finite current; first-order flux corrections are required.'),
      ('C9','Evaluating source rates exactly at h0 provides the moving-manifold net current','STATE_ACCURACY_VS_FLUX_ORDER_MISMATCH: solve N_qf j=Dh0 zdot-qdot_nonfast.','results/reduction/r5c_corrigendum/ck_fast_current_reconstruction.csv','CK rank-two canonical map identifies net currents; eta=1 flux accuracy remains descriptive.'),
      ('C10','Preserving 968 source IDs implies preserving 968 zero-order gross ledgers','SOURCE_PROVENANCE_PRESERVED differs from REDUCED_MODEL_ZERO_ORDER_OBSERVABLE_PRESERVED.','docs/reduction/reduction_decisions.csv','All source channels remain canonical; all 968 mechanistic decisions PENDING.')]
    corrections=[dict(issue_id=i,prior_statement_or_implication=p,status='CORRECTED_PRESENT_INTERPRETATION',corrected_statement=c,historical_evidence_affected=e,frozen_artifact_modified=False,scientific_consequence=s) for i,p,c,e,s in issues]
    write_csv(OUT/'interpretation_corrections.csv',corrections)
    obs=[
      ('A','T0,T1,B and 212 fast-invariant coordinates','PRESERVED_AT_ZERO_ORDER','high: slow resources and coupling',True,False,'0','Typically O(eta) away from startup, conditional on theorem hypotheses','fixed-source-scale state and total E_inf','must declare before validation'),
      ('A','ATP, protein Pept0003 and dynamic enzyme totals','PRESERVED_AT_ZERO_ORDER','high: energy/output/enzyme inventories','coordinate dependent','exact affine or h0 if needed','0','State-level accuracy measured; exact retained-coordinate membership must be listed','all241 state/output metrics','future candidate specific'),
      ('B','CP, CK_CP, CK_CP_ADP and free CK species','PRESERVED_AT_ZERO_ORDER','high for binding occupancy',False,True,'h0','O(eta) post-layer under valid singular limit; no uniform startup guarantee','fast-state E_inf in separate windows','future candidate specific'),
      ('C','27 SOURCE_GENERAL exact laws Lx','PRESERVED_EXACTLY','mandatory source invariants',False,True,'exact affine algebra','Exact structural preservation LS=0; roundoff and solver drift reported','L(x-x0), never x-x0-Sxi','mandatory structural check'),
      ('D','CK pair net j0,j1','RECONSTRUCTABLE_NET_CURRENT','redistribution and accounting',False,True,'leading finite O(1) kinematic current','Asymptotic current approximation requires regular derivative convergence and first-order offset; eta1 measured separately','N_qf j-Dh0 zdot+qdot_nonfast; absolute and fixed scaled source error','future candidate specific; not approved here'),
      ('E','CK equilibrium common forward/reverse circulation','DESCRIPTIVE_GROSS_FLUX_FROM_H0','turnover estimates',False,True,'leading eta^-1 gross circulation','Relative leading accuracy may improve while O(1) individual corrections remain absent','each directed rate with gross and net scales','descriptive only until declared'),
      ('E','Individual O(1) corrections to CK forward/reverse rates','REQUIRES_FIRST_ORDER_FLUX_RECONSTRUCTION','high if microscopic turnover required',False,'not implemented','1 or higher','Not supplied by h0 alone; CK kinetic derivative and stable fast Jacobian support a conditional reconstruction','individual rate/extent errors and initial-layer matching','requires prospective order and threshold'),
      ('G','Individual high-accuracy fast gross extents from h0 alone','NOT_IDENTIFIABLE_AT_ZERO_ORDER','turnover and isotope/microscopic ledgers',False,False,'0 insufficient','Net fixes only difference; common O(1) correction is absent. Strict eta0 gross extents generally diverge','separate directed integrals, numerical conditioning, startup contribution','cannot claim preserved without reconstruction'),
      ('F','Cumulative CK net redistribution extents','RECONSTRUCTABLE_NET_CURRENT','full-state accounting',False,'via current integration','leading finite current plus startup matching','Outer net extents need initial-layer redistribution offset; no new integration certified here','integrated net identity and ledger closure with declared offset','future candidate specific'),
      ('F','CK catalytic net 338 minus 339 extent from B loss','PRESERVED_AT_ZERO_ORDER','energy regeneration',False,True,'0 plus exact Bdot identity','Bdot=-v338+v339 is exact; state/total approximation governs extent error','B0-B(t) versus source','descriptive baseline only'),
      ('G','Exact source gross ledgers for all 968 channels','FULL_MODEL_ONLY','canonical provenance reference','source integration',False,'full source','Source integration supplies actual-parameter reference subject to measured numerical uncertainty','directed extent scores; distinguish exact laws','reference retained; reduction must declare required subset'),
      ('H','CK initial-layer states and net extent offset','FULL_MODEL_ONLY','startup/initial observables',True,'hybrid full startup','full layer or matched composite','Outer solution has no uniform t0 fast-state guarantee; hybrid switch may produce a disclosed jump','FULL_WINDOW / POST_INITIAL_LAYER / COMPOSITE_OR_HYBRID and switch jump','must prospectively declare treatment')]
    observable=[dict(category=a,observable=b,identifiability_label=c,scientific_importance=d,retained_directly=e,reconstructed=f,reconstruction_order=g,expected_asymptotic_accuracy=h,validation_metric=i,required_for_promotion=j) for a,b,c,d,e,f,g,h,i,j in obs]
    write_csv(OUT/'observable_identifiability.csv',observable)
    write_doc('r5c_reduction_observable_contract_v1.md', '''# Reduction observable contract v1 — additive R5-C

Every future candidate must freeze an observable contract before validation. This semantics requirement changes no historical R4 gate, threshold, condition, floor or initial value. The CK examples below do not authorize promotion or assign new thresholds. `observable_identifiability.csv` is the machine-readable companion.

For each observable specify: scientific importance; physical definition, units and source reaction/state IDs; directly retained coordinate or reconstruction map; order; expected asymptotic accuracy and hypotheses; domain and time window; validation metric, floor and numerical uncertainty budget; whether it is mandatory for promotion. Declare all required observables and thresholds prospectively. Source kinetics must be preserved and finite-parameter validation must match the intended scientific use.

| Class | CK example | Treatment / obligation |
|---|---|---|
| A slow states/totals | ATP, protein output, T0,T1,B, dynamic enzyme totals | List exact retained coordinates. ATP/output can use exact affine reconstruction; free CP is reconstructed, while B is a slow total. Totals are dynamic under non-fast reactions. Validate states, totals and output. |
| B fast states | CK_CP, CK_CP_ADP | h0 reconstruction, generally post-layer zero order; require explicit startup treatment. |
| C exact conservation | SOURCE_GENERAL laws | Structural LS=0 and reconstruction preservation; measure L(x-x0) separately. Exact algebra does not certify a numerical ledger. |
| D net currents | j332-333, j336-337 | Kinematic reconstruction using canonical N_qf, rank and any nullspace; validate finite-parameter accuracy separately. |
| E gross directed rates | each forward/reverse fast rate | h0 gives leading circulation only. Declare whether O(1) corrections are required and how they are derived. |
| F net extents | integral j; B0-B(t) for catalytic net conversion | Include matched startup redistribution offset or retain full startup; specify integration error. |
| G gross directed extents | integral v332, integral v333, all968 source ledgers | Retain canonical provenance mapping. Gross extent accuracy needs its own reconstruction order and uncertainty analysis; it does not follow from state accuracy. |
| H initial-layer observables | binding occupancy, startup extent and hybrid switch jump | FULL_WINDOW, POST_INITIAL_LAYER and COMPOSITE_OR_HYBRID must be distinct. Fix cutoff/matching/switch policy before scoring. |

Allowed labels: PRESERVED_EXACTLY; PRESERVED_AT_ZERO_ORDER; RECONSTRUCTABLE_NET_CURRENT; DESCRIPTIVE_GROSS_FLUX_FROM_H0; REQUIRES_FIRST_ORDER_FLUX_RECONSTRUCTION; NOT_IDENTIFIABLE_AT_ZERO_ORDER; FULL_MODEL_ONLY. Labels describe capability/order, not approval. PRESERVED_EXACTLY is reserved for proved algebraic identities; zero-order accuracy requires hypotheses and measured original-parameter evidence. NOT_IDENTIFIABLE_AT_ZERO_ORDER is order-specific, not a permanent prohibition on higher-order reconstruction.

CK supports a unique pair net current because N_qf has full rank. Knowing a difference alone leaves a common forward/reverse correction free; h0 kinetics fix leading circulation but do not supply that O(1) correction. CK's full kinetic derivative and attracting fast Jacobian can constrain a first-order displacement and hence separate gross corrections if explicitly derived and validated, with startup matching. No such flux reconstruction model or certificate is built here.

All 968 directed source channels remain provenance-visible. Certificates must carry two separate declarations: SOURCE_PROVENANCE_PRESERVED and the observable-by-observable REDUCED_MODEL_ZERO_ORDER_OBSERVABLE_PRESERVED capability. No zero-order claim covers all968 gross ledgers. PURE_reduced_core remains NOT_VALIDATED and all968 decisions PENDING.
''')
    write_doc('r5c_fast_ledger_semantics_v1.md', f'''# Fast ledger semantics v1 — R5-C

For each selected reversible pair define oriented j=v_forward-v_reverse from canonical stoichiometry. Directed rates and gross extents xi_forward=integral v_forward dt and xi_reverse=integral v_reverse dt are distinct observables. Slow stoichiometric dynamics see j. In the singular family both directed rates scale as eta^-1; their difference can remain O(1). Gross extents generally have no finite regular eta→0 limit on a fixed slow-time interval. Large opposite extents can produce a finite net change, amplifying cancellation and numerical sensitivity. State convergence alone establishes neither individual O(1) gross correction accuracy nor equally conditioned directed extent convergence. This is an accounting/order issue; no software bug is inferred.

Canonical CK reactions 332/333 bind/unbind CP with CK, and 336/337 bind/unbind CP with CK_ADP. Parsing canonical `models/pnas2017_full_reference/original/fMGG_synthesis.xml` and original author kinetics gives forward orientation toward CK_CP and CK_CP_ADP. The independent q=(CK_CP,CK_CP_ADP) rows yield N_qf={ck['N_qf']}, rank {ck['rank']}, nullspace dimension {ck['nullspace_dimension']}. It happens to be I; that is a derived result, not an assumption. Other coordinate choices must recheck rank and identifiable combinations and explicitly label any pseudoinverse convention.

Fast invariants include T0=CK+CK_CP, T1=CK_ADP+CK_CP_ADP, B=CP+CK_CP+CK_CP_ADP, with all239 full fast invariants or212 within the R1 class. They obey Lf Sf=0 but are not globally constant. q=h0(z); zdot=T S_nonfast v_nonfast(Phi(z)); qdot_manifold=Dh0 zdot. Therefore

    N_qf j_fast = Dh0 zdot - (S_nonfast v_nonfast)_q.

The full action is S_forward j_fast and satisfies dPhi/dz zdot=S_nonfast v_nonfast+S_forward j_fast. Representative R5 baseline rows include all212 z coordinates and their labels, full Dh0 and flow, both q kinematic terms, direct source pair currents and error metrics. Source-projected h0, outer and hybrid are distinguished. Identity max error is {ck['identity_max_absolute_error']:.6g}; full-state tangent identity error {ck['full_state_tangent_identity_max_error']:.6g}; Dh0 central-difference max scaled error {ck['Dh0_fd_scaled_error_max']:.6g}. Eta=1 representative post0.05 max scaled current error is {ck['post_0p05_representative_comparison']['hybrid']['max_scaled_error']:.6g} for hybrid using each pair's fixed full-trajectory post-layer scale. This is descriptive, not a flux acceptance certificate; pointwise relative errors become ill-conditioned near zero. Startup rows are explicitly outside outer post-layer validation.

At h0, leading binding equilibrium has v_forward^(0)=v_reverse^(0), hence zero leading net. Finite slow manifold motion generally requires a nonzero current. For q=h0+eta q1, the eta^-1 fast layer gives an O(1) contribution J_fast q1. In the frozen-invariant CK chart its order-one invariance equation is J_fast q1=Dh0 F0-qdot_nonfast, with S_forward action as above. Invertibility permits a conditional higher-order kinetic derivation; no q1 model is implemented. Evaluating rates exactly at h0 instead returns only numerical-roundoff net (measured max {ck['h0_net_roundoff_max']:.6g}). This is STATE_ACCURACY_VS_FLUX_ORDER_MISMATCH.

Level1: net stoichiometric current is kinematically identifiable in this chart. Level2: original finite eta kinetics at h0 give descriptive common leading circulation. Level3: individual high-accuracy O(1) gross corrections require displacement/kinetic derivatives and an explicit validated first-order reconstruction. Adding the same finite correction to both directions changes neither j nor its stoichiometric action, so zero-order state values plus net current alone cannot identify it. This does not make CK gross fluxes permanently unidentifiable: additional constitutive/order information can remove the freedom. Strict-limit divergent turnover must not be represented as a finite zero-order gross extent.

Net cumulative extents also need startup matching. A full initial state off h0 redistributes an O(1) amount in the fast layer. An outer integral starting from zero omits that offset; retain full startup or explicitly match it. Gross fast startup turnover and subsequent order-one corrections need separate accounting. No new extent integration has been certified.

Four different balance tests remain separate: L(x-x0) for exact source invariants; x-x0-Sxi for independently integrated directed extents; z-z0-TSxi for reduced slow coordinates; and algebraically reconstructed full-state residual. For x=c+Xz z+Dq, full residual decomposes as Xz times slow residual plus D times q tracking minus ledger change, with a consistently declared initial anchor. R5 measured maximum exact-law drift {balance['max_exact_law_drift']:.6g}, primary source ledger residual {balance['max_primary_source_ledger_residual']:.6g}, reduced slow residual {balance['max_reduced_slow_ledger_residual']:.6g}, and same-trajectory tight-extent variation {balance['max_same_trajectory_tight_extent_change']:.6g}. Exact source conservation failure was NOT observed. Complete state/dense-output/extent attribution remains MIXED / UNRESOLVED. R4 balance gates are frozen. Large algebraic full-ledger residuals must not be relabeled as broken source invariants.
''')
    post=gate['post_0p05_worst']; acc=eta['original_eta1_all241_post_0p05_max_scaled']
    write_doc('r5c_qssa_interpretation_corrigendum.md', f'''# R5-C QSSA / singular-perturbation interpretation corrigendum

Additive successor to frozen R1–R5 evidence; registration parent `6c11b585df42fb9aa5d5ea5d5e8be44f92e914a6`. Historical evidence records what was executed. This document corrects present interpretation without rewriting any historical result, criterion, summary or manifest. The correction matrix C1–C10 and evidence navigation are derived from hash-bound sources.

Global source geometry is SUPPORTING_GEOMETRIC_DIAGNOSTIC. A candidate need not align with the globally fastest same-dimensional Schur/CSP span. A defensible module reduction requires its singular limit, fast invariants, attracting frozen equilibrium, normal hyperbolicity on the declared domain, sufficiently slow forcing and quantitative original-parameter accuracy. A faster unrelated mode can remain dynamic. A 90-degree angle alone does not disprove all QSSA for a module. No inspected historical R3/R4 sentence explicitly stated a universal alignment theorem; this correction addresses the human-identified implication, while preserving already qualified source wording. `docs/reduction/r4_mixed_csp_mode_diagnostic.md` reports “Maximum temporal angle: 90 degrees” and states “Four modes are not four species.” Its strongly varying span and lack of a justified fixed chemical coordinate map rule out the naive proposed interpretation of replacing four fixed chemical species by four CSP modes. They do not prove that no nonlinear/moving slow manifold exists. Its historical NUMERICALLY_UNRESOLVED probe classification stays unchanged.

Candidate construction defaults to FAST_REACTION_PROCESS_FIRST: select Sf; derive Lf Sf=0 and slow totals z; define the singular scaling and critical manifold; establish fast-layer attraction; handle the initial layer; project non-fast flow. CK 332/333 and336/337 are fast CP binding/unbinding directions. CK_CP and CK_CP_ADP are not globally fast species by fiat: they also participate in slower catalytic and other network processes. Species-list QSSA requires independent derivation from a valid singular form. The CK derivation and canonical map support this distinction.

Initial-layer error differs from outer error. R5's stored initial jump is {eta['worst_initial_layer_jump']:.12g} in the inferred reference concentration convention; the initial relaxation time is {eta['tau0_s']:.12g} s, approximately10 microseconds. q(0)≠h0(z0) produces a fast layer. Zero-order outer states need not approximate every fast species uniformly at t0. R5's pure outer post-startup all241 maximum is {eta['original_eta1_all241_post_startup_max_scaled']['outer']:.12g}, while post0.05 outer is {acc['outer']:.12g}; hybrid post-startup and post0.05 all241 maximum is {acc['hybrid']:.12g}. The hybrid retains full startup and uses the registered10 eta tau0 switch; its disclosed switch projection and microscopic startup accounting remain separate observables. Future validation must distinguish FULL_WINDOW, POST_INITIAL_LAYER and COMPOSITE_OR_HYBRID.

R4 remains evaluated under its frozen full-window protocol, including the unfitted algebraic initialization jump. Recomputed arrays give worst post0.05 all241 state error: historical21 {post['HISTORICAL_R3_21']:.12g}; GlyRS-only {post['R4_GLYRS_ONLY']:.12g}; MetRS-only {post['R4_METRS_ONLY']:.12g}. These exceed the historical0.01 state accuracy level even after startup; this is a descriptive post-window comparison, not a retroactive additional gate. R4 family failures cannot be explained solely by startup mismatch.

Registered gates are state0.01, aminoacylation process directed rate0.05, extent0.01 and balance1e-8; the closure1e-10 guard is engineering. We recompute all measured tiers and uncertainty from primary/probe arrays and original scoring floors, not summary prose. The new CSV retains historical tier/overall statuses, registered thresholds and10% uncertainty budgets. State/rate/extent intervals use summed source/reduced envelopes; balance includes tighter ledger and gross representation evidence. These remain empirical probe-supported bounds, not rigorous exact-solution enclosures. If the registered uncertainty exceeds budget, characterization is unresolved. Controlled uncertainty plus lower bound above threshold is RESOLVED_FAIL; upper bound below threshold is RESOLVED_PASS; straddling is unresolved.

Across18 family-condition cases, state:18 RESOLVED_FAIL; rate:18 RESOLVED_FAIL; extent:16 RESOLVED_FAIL and2 RESOLVED_PASS; balance:18 NUMERICALLY_UNRESOLVED. Historical derived numbers reproduce exactly. All cases retain their old overall NUMERICALLY_UNRESOLVED status. The conjunction PASS_ALL_REGISTERED_GATES is logically impossible for each case because a mandatory state/rate failure is resolved under the registered uncertainty characterization. Complete numerical characterization is a different question.

The R4 summary's historical causal label was “UNDETERMINED_NUMERICAL_UNCERTAINTY_OR_NONCOMPLETION” (`docs/reduction/r4_fast_block_summary.md`). Correct present screen outcome: BOTH_FAMILY_CANDIDATES_FAIL_REGISTERED_GATE_SCREEN. Causal explanation of the historical combined21 failure: UNDETERMINED. The split experiments do not independently establish causal family defects, additive combination behavior or irrelevance of shared-resource coupling. Unresolved balance does not erase the screen failures; screen failures do not fully characterize every observable.

R3/R4 rejected specific tested zero-order graphs:21-state combined,9-state GlyRS,12-state MetRS, on the registered tested domain. H5 remains narrow. None establishes AMINOACYLATION_QSSA_IMPOSSIBLE, that all bound enzyme states must remain dynamic, that every partial equilibrium/QSSA fails, or that a global slow manifold cannot exist. CK supplies a methodological counterexample to blanket PURE irreducibility, without proving aminoacylation reducibility.

R5 CK is positive DESCRIPTIVE_BASELINE_EVIDENCE: the mechanism-first construction is asymptotically coherent on its declared binding subsystem and is highly accurate at eta=1 state level. Stored eta1,.3,.1,.03,.01 hybrid errors systematically decrease. Approximately3.38e-4 post-layer/hybrid state error is much smaller than the old graph errors, although CK reduces different chemistry and this comparison is not a controlled proof about aminoacylation. No global theorem/order claim follows from a finite scan. Broad conditions are unvalidated; authoritative absolute units incomplete; full physical-domain bounds unproven, including retained tiny negative roundoff; gross flux corrections unfinished; promotion criteria unapproved. Preserve CK_FAST_SUBSYSTEM_STRUCTURE_VERIFIED, CK_CRITICAL_MANIFOLD_ANALYTICALLY_DEFINED, CK_FAST_LAYER_ATTRACTING_ON_TESTED_DOMAIN, CK_SINGULAR_LIMIT_CONSISTENT, CK_ETA1_ACCURACY_DESCRIPTIVE and CK_REDUCTION_NOT_YET_PROMOTED.

GlyRS preserves ZERO_ORDER_GRAPH_ERROR_NOT_EXPLAINED_BY_LOCAL_TRANSVERSE_FORCING. Aperp=Gq−Dh0 Fq improves the lag predictor in7/9 conditions, not all. Moving-manifold feedback explains part of the old discrepancy but does not establish that a first-order correction to the same state block suffices. No GlyRS h1 model is built. Future human-reviewed methodology: inspect reaction mechanism → identify fast reaction subsets → derive invariants → distinguish rapid equilibrium from catalytic QSSA → construct a new singular limit. Species-membership subset enumeration is not the default next step.

R5 separates small exact-source-law drift from more sensitive directed ledgers; exact conservation failure was NOT observed. Complete state/dense/extent numerical attribution remains MIXED / UNRESOLVED. The new fast-ledger document derives CK net redistribution from manifold kinematics and explains STATE_ACCURACY_VS_FLUX_ORDER_MISMATCH, circulation divergence and order-specific gross identifiability. The observable contract is required before future validation; all968 channels stay source provenance and all968 mechanistic decisions stay PENDING. PURE_reduced_core remains NOT_VALIDATED. No scientific promotion, new screen, new solve, push or merge.

Methodological hierarchy: FAST REACTION PROCESS → FAST STOICHIOMETRIC INVARIANTS → SINGULAR LIMIT → CRITICAL MANIFOLD → FAST-LAYER ATTRACTIVITY → INITIAL-LAYER HANDLING → REDUCED SLOW FLOW → STATE RECONSTRUCTION → NET FLUX RECONSTRUCTION → GROSS-FLUX IDENTIFIABILITY CONTRACT → ORIGINAL-PARAMETER VALIDATION.

Primary theory context: [Eilertsen et al., open Michaelis–Menten singular perturbation](https://arxiv.org/abs/2101.05532) distinguishes fast reactions from species QSS settings; [Desoeuvres et al., reaction-network reduction with approximate conservation laws](https://arxiv.org/abs/2212.13474) explains why fast-subsystem first integrals require slow variables. These support methodology, not PURE numerical conclusions. The remaining order and accounting conclusions above follow from the explicit CK equations and repository evidence, rather than being attributed to those abstracts.

| Human-review question | Current answer |
|---|---|
| 1. Was global fastest-span geometry interpreted too strongly as a QSSA requirement? | Yes as a necessary-condition implication; stored diagnostics remain supporting, with no universal theorem inferred. |
| 2. Do both R4 family candidates decisively fail state/rate gates despite unresolved balance? | Yes, both tiers in all9 conditions for each family, under the frozen uncertainty protocol and conservative comparison envelopes. |
| 3. Are R4 post-layer errors too large for startup-only explanation? | Yes, verified maxima0.0371711 and0.141077, historical21 0.141077. |
| 4. Does R5 CK achieve much smaller state error through a mechanism-first singular limit? | Yes descriptively at baseline eta1, with decreasing eta errors; no aminoacylation theorem or promotion. |
| 5. Is exact conservation failure responsible for R4/R5 balance problems? | No observed source exact-law failure in R5 decomposition. Complete numerical/accounting causality remains unresolved. |
| 6. Can CK net fast redistribution be reconstructed? | Yes uniquely from canonical rank-two N_qf and manifold kinematics; eta1 current accuracy remains separately descriptive. |
| 7. Does zero-order CK uniquely guarantee accurate individual gross directed extents? | No. Leading circulation is available; separate O(1) corrections and startup matching require additional reconstruction and validation. |
| 8. What must future validation contract specify? | All A–H observable classes, importance, retention/reconstruction/order, asymptotic hypotheses, windows, metrics, uncertainty and promotion obligations before validation. |
''')
    nav=[]
    for item in corrections:
        source=item['historical_evidence_affected']; nav.append({'node':item['issue_id'],'classification':'INFERRED' if item['issue_id'] in ['C1','C2','C6','C8','C10'] else 'EXTRACTED','claim':item['corrected_statement'],'evidence_path':source,'source_sha256':sha(ROOT/source),'freshness':'HASH_CHECK_REQUIRED','authority':'DERIVED_NAVIGATION_NOT_SOURCE_AUTHORITY'})
    write_json(OUT/'evidence_navigation.json',{'nodes':nav,'ambiguities':[{'classification':'AMBIGUOUS','claim':'combined-block causal explanation UNDETERMINED'},{'classification':'AMBIGUOUS','claim':'state/dense/extent numerical attribution MIXED / UNRESOLVED'}]})
    print('R5-C additive interpretation and observable contract written')

if __name__=='__main__':main()
